CREATE DATABASE IF NOT EXISTS LAB2B_IIITDM;
USE LAB2B_IIITDM;
CREATE TABLE IF NOT EXISTS STUDENT(S_ID VARCHAR(10) NOT NULL PRIMARY KEY,FNAME VARCHAR(10),LNAME VARCHAR(10),PARENT VARCHAR(10),AGE INT);
CREATE TABLE IF NOT EXISTS FACULTY(F_id VARCHAR(10) NOT NULL PRIMARY KEY,F_NAME VARCHAR(10), Age INT, department VARCHAR(10), JOINDATE DATE);
CREATE TABLE IF NOT EXISTS BUILDINGS(B_NAME VARCHAR(10), B_ID VARCHAR(10) NOT NULL PRIMARY KEY,CAP INT, NUMBFLOORS INT,INGDATE DATE);

INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('1','VISHNU','AP','ABHAY',20);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('2','RAM','RAO','RAJ',20);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('3','VENU','VARMA','VIJAY',20);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('4','SUMA','SHARMA','RAHUL',20);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('5','BHEEM','SETTY','SENA',20);

INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F01','RAM',32,'CSE','2014-10-10');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F02','HRITIK',35,'CSE','2018-09-25');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F03','RAMESH',28,'CSE','2020-12-10');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F04','SOMESH',38,'ECE','2016-07-29');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F05','VIJAY',40,'MECH','2007-05-27');

INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('ASHOKA','B01',800,14,'2014-01-01');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('ASWATHA','B02',1050,14,'2012-02-02');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('JASMINE','B03',500,14,'2019-03-03');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('LOTUS','B04',100,1,'2014-03-04');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('ARJUN','B05',85,3,'2017-05-20');

SELECT * FROM STUDENT;
SELECT * FROM FACULTY;
SELECT * FROM BUILDINGS;

INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F11','SHIVANI',27,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F12','PUNYA',28,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F13','SHASHI',29,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F14','DHYAN',26,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F15','RISHI',28,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F16','ANUSHA',31,'CSE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F17','ADITI',32,'ECE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F18','PARAM',45,'ECE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F19','AKASH',46,'ECE','2021-01-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F20','VIVAN',39,'ECE','2021-01-01');

INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('11','JASSY','SINGH','GURU',19);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('12','SHIVAM','SWAMY','VENKAT',19);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('13','VIRU','BISHNI','SOIMNOI',19);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('14','VIRAT','KOHLI','MAHI',19);
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE)VALUES('15','SINDHU','PV','GOPI',19);

INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('GANGA','B11',500,10,'2020-12-25');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('KALI','B12',800,12,'2020-12-25');
INSERT INTO BUILDINGS(B_NAME, B_ID,CAP, NUMBFLOORS,INGDATE)VALUES('BHADRA','B13',2000,17,'2020-12-25');

SELECT * FROM STUDENT;
SELECT * FROM FACULTY;
SELECT * FROM BUILDINGS;

INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F21','JASPRIT',31,'ECE','2021-03-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F22','LOKESH',32,'ECE','2021-03-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F23','RAHUL',33,'ECE','2021-03-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F24','DEEPAK',32,'ECE','2021-03-01');
INSERT INTO FACULTY(F_id,F_NAME, Age, department, JOINDATE)VALUES('F25','SHARDUL',31,'ECE','2021-03-01');

UPDATE FACULTY SET DEPT='MECH' WHERE S_ID='F21';
UPDATE FACULTY SET DEPT='MECH' WHERE S_ID='F22';
UPDATE FACULTY SET DEPT='MECH' WHERE S_ID='F23';
UPDATE FACULTY SET DEPT='MECH' WHERE S_ID='F24';
UPDATE FACULTY SET DEPT='MECH' WHERE S_ID='F25';

ALTER TABLE STUDENT
ADD COLUMN DEPT VARCHAR(10);

UPDATE STUDENT SET DEPT='CSE' WHERE S_ID='1';
UPDATE STUDENT SET DEPT='CSE' WHERE S_ID='2';
UPDATE STUDENT SET DEPT='CSE' WHERE S_ID='3';
UPDATE STUDENT SET DEPT='CSE' WHERE S_ID='4';
UPDATE STUDENT SET DEPT='CSE' WHERE S_ID='5';
UPDATE STUDENT SET DEPT='MATH' WHERE S_ID='11';
UPDATE STUDENT SET DEPT='MATH' WHERE S_ID='12';
UPDATE STUDENT SET DEPT='MATH' WHERE S_ID='13';
UPDATE STUDENT SET DEPT='PHY' WHERE S_ID='14';
UPDATE STUDENT SET DEPT='PHY' WHERE S_ID='15';

DELETE FROM STUDENT WHERE DEPT="MATH" AND S_ID=11;
DELETE FROM STUDENT WHERE DEPT="MATH" AND S_ID=12;
DELETE FROM STUDENT WHERE DEPT="PHY" AND S_ID=15;

DELETE FROM BUILDINGS WHERE B_ID='B01';

SELECT * FROM STUDENT;
SELECT * FROM FACULTY;
SELECT * FROM BUILDINGS;

ALTER TABLE STUDENT ADD COLUMN MARKS_IN_PER VARCHAR(10);

UPDATE STUDENT SET MARKS_IN_PER='90' WHERE S_ID='1';
UPDATE STUDENT SET MARKS_IN_PER='95' WHERE S_ID='2';
UPDATE STUDENT SET MARKS_IN_PER='100' WHERE S_ID='3';
UPDATE STUDENT SET MARKS_IN_PER='95' WHERE S_ID='4';
UPDATE STUDENT SET MARKS_IN_PER='98' WHERE S_ID='5';
UPDATE STUDENT SET MARKS_IN_PER='85' WHERE S_ID='13';
UPDATE STUDENT SET MARKS_IN_PER='75' WHERE S_ID='14';

INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('16','RAM','KUMAR','SAMPAT',18,'CSE','99');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('17','ANIL','ROY','NAG',18,'CSE','99');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('18','GURU','BASU','CHANDER',18,'CSE','99');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('19','ALIA','KAPUR','MAHESH',18,'ECE','99');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('20','KIARA','BHAT','AJAY',18,'CSE','99');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('21','ROBERT','SHARMA','MANVANT',18,'MECH','100');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('22','BIPIN','SEN','KIRAN',18,'PHY','100');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('23','RAJA','REDDY','SAMPAT',18,'ECE','100');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('24','CHARAN','NAIDU','HIRAM',18,'ECE','100');
INSERT INTO STUDENT(S_ID,FNAME,LNAME,PARENT,AGE,DEPT,MARKS_IN_PER)VALUES('25','RIZWAN','KHAN','SHAH',18,'MECH','100');

ALTER TABLE BUILDINGS DROP COLUMN INGDATE;

ALTER TABLE BUILDINGS ADD COLUMN STF_ID VARCHAR(10);

UPDATE BUILDINGS SET STF_ID='S01' WHERE B_ID='B02';
UPDATE BUILDINGS SET STF_ID='S02' WHERE B_ID='B03';
UPDATE BUILDINGS SET STF_ID='S03' WHERE B_ID='B04';
UPDATE BUILDINGS SET STF_ID='S04' WHERE B_ID='B05';
UPDATE BUILDINGS SET STF_ID='S09' WHERE B_ID='B11';
UPDATE BUILDINGS SET STF_ID='S10' WHERE B_ID='B12';
UPDATE BUILDINGS SET STF_ID='S11' WHERE B_ID='B13';

