CREATE DATABASE IF NOT EXISTS DBLAB;
USE DBLAB;
CREATE TABLE IF NOT EXISTS STUDENT( Rollno varchar (10), SName varchar (10), City varchar (10));
CREATE TABLE IF NOT EXISTS COURSE (CID varchar(10), CName varchar(10), Credit int(100));
INSERT INTO STUDENT(Rollno , SName, City)VALUES('1','VISHNU','HUBLI');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('2','RAM','HYDERBAD');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('3','SAM','PUNE');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('4','SHYAM','DELHI');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('5','JOHN','HUBLI');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('6','HARI','PUNE');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('7','GIRI','DELHI');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('8','MIRA','HUBLI');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('9','KIA','HYDERBAD');
INSERT INTO STUDENT(Rollno , SName, City)VALUES('10','ASHA','DELHI');
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS1','DBMS',4);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS2','COA',4);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS3','PC',3);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS4','TOC',4);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS5','DSA',3);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('CS6','DAA',4);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('EC1','OPTICS',3);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('EC2','EM',3);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('ME1','MATERIALS',3);
INSERT INTO COURSE(CID,Cname,Credit)VALUES('ME2','ADVMECH',4);

SELECT * FROM STUDENT;
SELECT * FROM COURSE;

ALTER TABLE STUDENT
ADD COLUMN DEPT VARCHAR(10);
ALTER TABLE STUDENT
ADD COLUMN MARKS INT;
UPDATE STUDENT SET DEPT='CSE',MARKS=95 WHERE Sname='VISHNU';
UPDATE STUDENT SET DEPT='CSE',MARKS=85 WHERE Sname='RAM';
UPDATE STUDENT SET DEPT='CSE',MARKS=90 WHERE Sname='SAM';
UPDATE STUDENT SET DEPT='CSE',MARKS=80 WHERE Sname='SHYAM';
UPDATE STUDENT SET DEPT='CSE',MARKS=75 WHERE Sname='JOHN';
UPDATE STUDENT SET DEPT='CSE',MARKS=68 WHERE Sname='HARI';
UPDATE STUDENT SET DEPT='ECE',MARKS=95 WHERE Sname='GIRI';
UPDATE STUDENT SET DEPT='ECE',MARKS=70 WHERE Sname='MIRA';
UPDATE STUDENT SET DEPT='MECH',MARKS=65 WHERE Sname='KIA';
UPDATE STUDENT SET DEPT='MECH',MARKS=88 WHERE Sname='ASHA';

UPDATE STUDENT SET MARKS=70 WHERE DEPT='MECH';

ALTER TABLE COURSE
MODIFY COLUMN CREDIT VARCHAR (10);

ALTER TABLE COURSE
ADD COLUMN COUR_ADMSN YEAR;





