CREATE DATABASE IF NOT EXISTS LAB3_IIITDM;
USE LAB3_IIITDM;
CREATE TABLE IF NOT EXISTS STUDENT(RollNo varchar (8) NOT NULL PRIMARY KEY, SName varchar (20), Gender char (1), City varchar(20));
CREATE TABLE IF NOT EXISTS COURSE(CCode char(5) NOT NULL PRIMARY KEY, CName varchar(20), Credit smallint);
CREATE TABLE IF NOT EXISTS ENROLLED(RollNo char(8) NOT NULL, CCode char(5) NOT NULL, YoE int,FOREIGN KEY (RollNo) REFERENCES STUDENT(RollNo),FOREIGN KEY (CCode) REFERENCES COURSE(CCode));

INSERT INTO STUDENT(RollNo, SName, Gender, City)VALUES('1901CS01','AAKASH','M','CHENNAI');
INSERT INTO STUDENT(RollNo, SName, Gender, City)VALUES('1901CS99','APEKSHA','F','DELHI');
INSERT INTO STUDENT(RollNo, SName, Gender, City)VALUES('2001CS10','VISHNU','M','HUBLI');
INSERT INTO STUDENT(RollNo, SName, Gender, City)VALUES('1801CS01','AALIYA','F','PUNE');
INSERT INTO STUDENT(RollNo, SName, Gender, City)VALUES('1801EC20','RESHMA','F','DELHI');

INSERT INTO COURSE(CCode, CName, Credit)VALUES('CS300','TOC',4);
INSERT INTO COURSE(CCode, CName, Credit)VALUES('CS500','DSA',3);
INSERT INTO COURSE(CCode, CName, Credit)VALUES('EC500','VLSI',2);
INSERT INTO COURSE(CCode, CName, Credit)VALUES('ME400','SME',5);
INSERT INTO COURSE(CCode, CName, Credit)VALUES('CS800','DBMS',5);

INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS01'),(SELECT CCode FROM COURSE WHERE CCode='CS300'),2019);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS01'),(SELECT CCode FROM COURSE WHERE CCode='CS500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS01'),(SELECT CCode FROM COURSE WHERE CCode='CS800'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS01'),(SELECT CCode FROM COURSE WHERE CCode='ME400'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS01'),(SELECT CCode FROM COURSE WHERE CCode='EC500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS99'),(SELECT CCode FROM COURSE WHERE CCode='CS300'),2019);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1901CS99'),(SELECT CCode FROM COURSE WHERE CCode='EC500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='2001CS10'),(SELECT CCode FROM COURSE WHERE CCode='CS500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='2001CS10'),(SELECT CCode FROM COURSE WHERE CCode='ME400'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801CS01'),(SELECT CCode FROM COURSE WHERE CCode='CS500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801CS01'),(SELECT CCode FROM COURSE WHERE CCode='CS800'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801CS01'),(SELECT CCode FROM COURSE WHERE CCode='ME400'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801CS01'),(SELECT CCode FROM COURSE WHERE CCode='EC500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801EC20'),(SELECT CCode FROM COURSE WHERE CCode='EC500'),2020);
INSERT INTO ENROLLED VALUES((SELECT RollNo FROM STUDENT WHERE RollNo='1801EC20'),(SELECT CCode FROM COURSE WHERE CCode='CS300'),2018);

ALTER TABLE COURSE ADD COLUMN CType varchar(20);

UPDATE COURSE SET CType='OPEN ELECTIVE' WHERE CCode='CS300';
UPDATE COURSE SET CType='OPEN ELECTIVE' WHERE CCode='CS500';
UPDATE COURSE SET CType='ELECTIVE' WHERE CCode='CS800';
UPDATE COURSE SET CType='ELECTIVE' WHERE CCode='EC500';
UPDATE COURSE SET CType='CORE' WHERE CCode='ME400';

SELECT * FROM COURSE;

ALTER TABLE STUDENT ADD COLUMN EMAIL varchar(30);

UPDATE STUDENT SET EMAIL='aakash@gmail.com' WHERE RollNo='1901CS01';
UPDATE STUDENT SET EMAIL='apeksha@gmail.com' WHERE RollNo='1901CS99';
UPDATE STUDENT SET EMAIL='vishnu@yahoo.com' WHERE RollNo='2001CS10';
UPDATE STUDENT SET EMAIL='aaliya@iiitdm.com' WHERE RollNo='1801CS01';
UPDATE STUDENT SET EMAIL='reshma@yahoo.com' WHERE RollNo='1801EC20';

SELECT * FROM COURSE;
SELECT * FROM STUDENT;

SELECT CName FROM COURSE WHERE CCode LIKE'CS%';

SELECT SName FROM STUDENT WHERE Gender='M' AND SName LIKE'%A%A%';

SELECT DISTINCT RollNo FROM ENROLLED WHERE YoE NOT IN (2018, 2019);

SELECT CCode FROM COURSE WHERE Credit IN (SELECT MIN(Credit) FROM COURSE);

SELECT DISTINCT CName FROM COURSE WHERE CCode IN (SELECT CCode FROM ENROLLED WHERE NOT YoE=2020);

SELECT City, COUNT(RollNo) FROM Student GROUP BY City;

SELECT RollNo,COUNT(RollNo) FROM ENROLLED GROUP BY RollNo HAVING COUNT(RollNo)=5;

SELECT RollNo,COUNT(RollNo) FROM ENROLLED WHERE RollNo='1901CS99';

SELECT CName,CCode FROM COURSE WHERE CCode LIKE'__5%';

SELECT RollNo,SName FROM STUDENT WHERE RollNo LIKE'%CS%';

SELECT RollNo,COUNT(RollNo) FROM ENROLLED GROUP BY RollNo HAVING COUNT(RollNo)>=4 AND YoE=2020;

SELECT CCode,COUNT(DISTINCT(CCode)) FROM ENROLLED WHERE CCode IN (SELECT CCode FROM ENROLLED WHERE RollNo IN (SELECT RollNo FROM STUDENT WHERE Gender='F' AND City='DELHI'));

SELECT SName FROM STUDENT WHERE EMAIL LIKE'%@gmail.com' OR EMAIL LIKE'%@yahoo.com';


