CREATE DATABASE LAB4A_CS20B1129;
SHOW DATABASES;
USE LAB4A_CS20B1129;
CREATE TABLE IF NOT EXISTS STUDENTACCOUNT
(
    ID INT NOT NULL PRIMARY KEY,
    PERSON_NAME VARCHAR(30) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    BIRTH DATE NOT NULL
);
INSERT INTO STUDENTACCOUNT VALUES(1, "RAMESH", "CS", '2001-01-12');
INSERT INTO STUDENTACCOUNT VALUES(2, "SURESH", "IT", '2020-02-20');
INSERT INTO STUDENTACCOUNT VALUES(3, "JOMIN", "CS", '1996-02-29');
INSERT INTO STUDENTACCOUNT VALUES(4, "SHREE", "IT", '2012-12-18');
INSERT INTO STUDENTACCOUNT VALUES(5, "HEMANTH", "CS", "2022-02-07");
SELECT * FROM STUDENTACCOUNT;

ALTER TABLE STUDENTACCOUNT ADD COLUMN AGE INT;

UPDATE STUDENTACCOUNT SET AGE=(year(curdate())-year(birth)) WHERE ID=1;
UPDATE STUDENTACCOUNT SET AGE=(year(curdate())-year(birth)) WHERE ID=2;
UPDATE STUDENTACCOUNT SET AGE=(year(curdate())-year(birth)) WHERE ID=3;
UPDATE STUDENTACCOUNT SET AGE=(year(curdate())-year(birth)) WHERE ID=4;
UPDATE STUDENTACCOUNT SET AGE=(year(curdate())-year(birth)) WHERE ID=5;

SELECT * FROM STUDENTACCOUNT;

SELECT * FROM STUDENTACCOUNT WHERE PERSON_NAME LIKE '%S%';

SELECT PERSON_NAME FROM STUDENTACCOUNT WHERE length(PERSON_NAME)=5;

SELECT * FROM STUDENTACCOUNT WHERE (ID%2)=1;